In [36]:
import numpy as np 
import matplotlib.pyplot as plt 
import pandas as pd 
import seaborn as sns
import math

In [2]:
dados = np.array([160, 165, 167, 164, 160, 166, 160, 161, 150, 152, 173, 160, 155,
                 164, 168, 162, 161, 168, 163, 156, 155, 169, 151, 170, 164,
                 155, 152, 163, 160, 155, 157, 156, 158, 158, 161, 154, 161, 156, 172, 153])

In [3]:
dados = np.sort(dados)

In [4]:
print(dados)

[150 151 152 152 153 154 155 155 155 155 156 156 156 157 158 158 160 160
 160 160 160 161 161 161 161 162 163 163 164 164 164 165 166 167 168 168
 169 170 172 173]


In [10]:
minimo = dados.min()
maximo = dados.max()

In [12]:
np.unique(dados, return_counts=True)

(array([150, 151, 152, 153, 154, 155, 156, 157, 158, 160, 161, 162, 163,
        164, 165, 166, 167, 168, 169, 170, 172, 173]),
 array([1, 1, 2, 1, 1, 4, 3, 1, 2, 5, 4, 1, 2, 3, 1, 1, 1, 2, 1, 1, 1, 1],
       dtype=int64))

In [28]:
# Número de Classes
n = len(dados)
i = round(1+3.3 * np.log10(n))
i

6

In [38]:
# Amplitude do intervalo h = AA/1  AA = Xmax - Xmin
h = math.ceil((maximo - minimo)/i) # math ceil eredonda o valor para cima
h

4

In [50]:
# Construção da distruibuição de frequência
intervalos = np.arange(minimo, maximo + 2, step = h)
intervalos

array([150, 154, 158, 162, 166, 170, 174])